name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-apache

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring
        env:
          update: true
      - name: Install composer dependencies
        run: |
          composer install --prefer-dist --no-scripts -q -o;
      - name: Set custom php.ini settings
        run: echo 'short_open_tag=off' >> /usr/local/etc/php/php.ini
      - name: Run Testsuite
        run: vendor/phpunit/phpunit/phpunit src/tests/