name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-apache

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
      - name: Install composer dependencies
        run: |
          composer install --prefer-dist --no-scripts -q -o;
      - name: Set custom php.ini settings
        run: echo 'short_open_tag=off' >> /usr/local/etc/php/php.ini
      - name: Run Testsuite
        run: vendor/phpunit/phpunit/phpunit src/tests/