name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-apache

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
      - name: Install composer dependencies
        run: |
          composer install --prefer-dist --no-scripts -q -o;
      - name: Set custom php.ini settings
        run: echo 'short_open_tag=off' >> /usr/local/etc/php/php.ini
      - name: Run Testsuite
        run: vendor/phpunit/phpunit/phpunit src/tests/