name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-apache

    steps:
      - uses: actions/checkout@v2
      - name: composer install
        uses: php-actions/composer@master
        with:
          command: install
          only_args: --prefer-dist --no-scripts -q -o
      - name: Run Testsuite
        run: vendor/phpunit/phpunit/phpunit src/tests/
